version: '3'
services:
    mysql:
      image: "mysql"
      container_name: "mysql-test"
      environment:
        - MYSQL_ROOT_PASSWORD=123456
        - MYSQL_DATABASE=iot
        - MYSQL_USER=iot
        - MYSQL_PASSWORD=123456
      ports:
        - 3306:3306
      networks:
        - mysql-network
      volumes:
        - /etc/localtime:/etc/localtime
        - ./data:/var/lib/mysql
networks:
  mysql-network:
    driver: bridge

#
# mysql -hlocalhst -uroot -p123456
#