version: '3'
services:
  emqx:
    image: "emqx/emqx:latest"
    container_name: "emqx-latest"
    environment:
      - EMQX_LOADED_PLUGINS="emqx_management,emqx_auth_username,emqx_dashboard"
      - EMQX_DASHBOARD__DEFAULT_USER__LOGIN=admin
      - EMQX_DASHBOARD__DEFAULT_USER__PASSWORD=iot@2020
      - EMQX_MQTT__MAX_PACKET_SIZE=16MB
      - EMQX_MANAGEMENT__DEFAULT_APPLICATION__ID=iot
      - EMQX_MANAGEMENT__DEFAULT_APPLICATION__SECRET=123456
      - EMQX_AUTH__USER__1__USERNAME=user
      - EMQX_AUTH__USER__1__PASSWORD=123456
      - EMQX_ALLOW__ANONYMOUS=false
      - EMQX_AUTH__USER__PASSWORD_HASH=plain
    ports:
     - 18083:18083
     - 1883:1883
     - 8081:8081
    #volumes:
     #- ./log:/opt/emqx/log
     #- /etc/localtime:/etc/localtime
    restart: always